version: '3.1'

services:
  postgres:
    image: postgres
    container_name: postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: mike
      POSTGRES_PASSWORD: 1111
      POSTGRES_DB: diploma_validator
    volumes:
      - ./data/postgres:/var/lib/postgresql/data
